### ISSUE TITLE
What if one genome has m2 and m4 mutations when the NUM_GRNAS is 2?

### ISSUE THREAD

**Issue by JiaoBingke** [MesserLab/Homing_Mechanisms_with_multiplexed_gRNAs#2]
Hi, Sam.
In the panmictic_simple.slim, the NUM_GRNAS is set to be 2 and the annotation is shown below.
```
// Element is NUM_GRNAS long, each spot on the element representing a GRNA target location.
    initializeGenomicElement(g1, 0, NUM_GRNAS - 1);
```
And in the 1 early() event, new individuals' genomes will be added m1 mutations in the two loci, say c(0,1). It's a little confusing. Because in a real organism,  the m1(wild type) only exists in one locus. But I think  compatible sentences in program somewhere else had been written to deal with this design.

My question is on the function of germline().
```
//// FUNCTION FOR GERMLINE RESISTANCE AND HOMING DRIVE.
function (void)germline(o<Genome>$ child_chromosome, o<Individual>$ parent, f$ resistance_rate) {
    // Determine presence of drive in this parent.
    parent_drive_count = sum(parent.genomes.countOfMutationsOfType(m2) == NUM_GRNAS);
    // If parent doesn't have drive allele, nothing happens in germline.
    if (!parent_drive_count)
        return;

    // Chromosome must have wt to cut, or nothing happens.
    if (child_chromosome.countOfMutationsOfType(m1) == 0)
        return;

    // Vector of possible loci for cas9 to cut:
    wt_loci = child_chromosome.positionsOfMutationsOfType(m1);

    // At each possible locus...
    for (i in seqAlong(wt_loci)) {
        // Check to see if cas9 cuts...
        if (runif(1) < HOMING_PHASE_CUT_RATE) {
            if (runif(1) < resistance_rate) {
                // Resistance forms:
                addResistanceAllele(child_chromosome, wt_loci[i]);
            }
            else {
                // If sucessfully cuts, but no res, then hdr fully succeeds:
                for (j in seqLen(NUM_GRNAS))
                    child_chromosome.addNewDrawnMutation(m2, j);
                return;
            }
        }
    }
}
```
The wt_loci=c(0,1). I suppose that in the first time of outer loop, the program enters the statement `for(j in seqLen(NUM_GRNAS))`. Then the child_chromosome will be added m2 mutation in two positions, say c(0,1). In the second time of outer loop, suppose the judge statement of` if (runif(1) < resistance_rate)` is true, then the `addResistanceAllele` function will add a mutation, supposing it's m4, to the child_chromosome in position of c(1). So the child_chrosome has two mutation m2 and m4 in c(0,1) positions. 

It's a low probability event since the resistance_rate is 0.02, quite small. But what if this event happens? What's the meaning of this c(m2, m4) mutations? In my opinion, the c(m2, m4) is the same as c(m2, m2) since once the HDR succeeds in one locus, whether other cutting loci become resistant or not has no relation with the result. What's your opinion? Thank you for any reply.

**Comment by samchamper** [comment]
Hey!

This is one of those cases that could have been made more clear by me including more thorough comments in my code. But the case that you describe is not actually possible. Your understanding of the mechanism in question is exactly correct: if HDR succeeds in any one locus, the drive is considered to have successfully replicated itself, and therefore will necessarily be present at all target sites.

The control flow of the block of code you've highlighted prevents any (m2, m4) individuals from coming into existence. The "return" statement (line 124) in the "else" block means that, as soon as HDR succeeds at any locus, the outer "for" loop will immediately end, and the function will exit with the chromosome set to m2 at all target sites. Some additional comments would have made this all easier to read, but hopefully it's clear now!

**Comment by JiaoBingke** [comment]
Oh, I did not notice the "return" statement(line 124). Now I understand. Thanks for your quick and clear reply.
